# Generated by Django 5.2.8 on 2025-11-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
